# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_clip_dcd_optimizer <- function(H, q, lb, ub, eps, max_steps, u) {
    .Call(`_SupportVectorLab_cpp_clip_dcd_optimizer`, H, q, lb, ub, eps, max_steps, u)
}

cpp_rbf_kernel <- function(x1, x2, gamma, symmetric = 1L) {
    .Call(`_SupportVectorLab_cpp_rbf_kernel`, x1, x2, gamma, symmetric)
}

cpp_linear_kernel <- function(x1, x2) {
    .Call(`_SupportVectorLab_cpp_linear_kernel`, x1, x2)
}

cpp_poly_kernel <- function(x1, x2, degree, coef0) {
    .Call(`_SupportVectorLab_cpp_poly_kernel`, x1, x2, degree, coef0)
}

cpp_chol_solve <- function(A, b) {
    .Call(`_SupportVectorLab_cpp_chol_solve`, A, b)
}

cpp_inverse_spd <- function(A) {
    .Call(`_SupportVectorLab_cpp_inverse_spd`, A)
}

